name: docs

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - uses: actions/checkout@master
      with:
        # otherwise, you will failed to push refs to dest repo
        fetch-depth: 0

    - name: Install Dependencies
      run: |
        pip install -e .
        pip install -r Docs/requirements.txt
        sudo apt-get install doxygen graphviz -y

    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with:
        documentation_path: ./Docs

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
